disabled_rules:
  - opening_brace
  - trailing_comma
  - todo
  - force_cast
nesting:
  type_level: 2
line_length:
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  warning: 300 # long lines will be truncated by SwiftFormat
  error: 300
type_body_length:
  warning: 500
  error: 800
function_body_length:
  warning: 300
  error: 500
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true
large_tuple:
  warning: 3
  error: 4
identifier_name:
  excluded:
    - vm
    - db
    - id
    - i
    - j
    - x
    - y
    - d
    - on
    - us
    - at
  allowed_symbols: ["_"]
type_name:
  excluded:
    - ID
cyclomatic_complexity:
  warning: 20
  error: 25
